### ISSUE TITLE
Keep data on local machines and don't upload to GitHub

### ISSUE THREAD

**Issue by ccurtis7** [theicechol/metamoles#4]
It is best practice to not upload datasets to GitHub (datasets may not have open source license, datasets may be too big and exceed GitHub's storage limits, keep datasets and software separate) other than maybe an example dataset for users to test out your code.

I would recommend sharing datasets with team members privately instead of uploading them to GitHub. Not a hard rec, but something to consider.

**Comment by elliej3** [comment]
@ccurtis7 Thank you for bringing this to our attention! We will consider these implications moving forward. It will depend on the structure of our final package.
